### ISSUE TITLE
action/command after the cutscene end

### ISSUE THREAD

**Issue by Kanorto** [PluginBugs/Issues-CinematicStudio#42]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I need write command after cutscene end. How?

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Script language

**Comment by LoneDev6** [comment]
Will be implemented.
