### ISSUE TITLE
Avoid re-showing inventory content on click during the cutscene

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-CinematicStudio#45]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

1. The player can remove the pumpkin by left-clicking on it during the cinematic.

2. Clicking on the inventory item brings back the old inventory (but fortunately we can't move anything).

3. If I have a cosmetic hat, the pumpkin disappears as soon as the cinematic is launched.

### Steps to reproduce the issue

https://www.youtube.com/watch?v=157Rd8f-XAA

### Server version

purpur 1996 1.20.1

### CinematicsStudio Version

1.4.4

### ProtocolLib Version

5.1.0 SNAPSHOT 654

### LoneLibs Version

1.0.25

### FULL server log

/

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=157Rd8f-XAA

**Comment by LoneDev6** [comment]
Why are your players clicking on the inventory and on the hat slot during cinematic?

**Comment by Weyl1** [comment]
I don't know, because they can do it, but I think it would be better to block it completely. ^^'

**Comment by LoneDev6** [comment]
I'll check if this is possible to fix, anyway people won't generally click on inventories during cutscenes, I don't think you should really worry about that.

**Comment by Weyl1** [comment]
And for the head cosmetic ? because this one totally removes the pumpkin.
