### ISSUE TITLE
Loop a section of the cinematic

### ISSUE THREAD

**Issue by nightway1** [PluginBugs/Issues-CinematicStudio#46]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

My idea is can loop a section of a cinematic for i mean... make a menu in game for better look or something in that style

### Is your feature request related to a problem?

I want to make a menu ingame to my server, and i need than the animation loops indefinitely until the player execute a command and now only i can only make a hypergigant timeline than repeat the animation of panning

### Describe alternatives you've considered

nothing more than that, would help space, and simplify the storage of the cinematics for that purpose

**Comment by LoneDev6** [comment]
I see this useful only for a cinematic which is showcasing server rules on a wall or something, which requires players to run `/accept` command, for example.
Right now I have no clear way to implement that in the code and on the admin panel side.
Do you have any idea?
