### ISSUE TITLE
NPCs no longer display their equiped handheld items.

### ISSUE THREAD

**Issue by EnderOliver4142** [PluginBugs/Issues-CinematicStudio#52]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Whenever I give a an item to an NPC in their mainhand or offhand slot, it never appears in the cutscene. If I hold the item while recording movement for the NPC, the same thing happens. Please fix this.

### Steps to reproduce the issue

1. Create cutscene
2. Create NPC holding an item
3. Set up camera and play cutscene
4. View the NPC without the item :((

### Server version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/58921480/895887f5-3ea0-4e72-8c75-358f5f69a177)

### CinematicsStudio Version

version 1.4.4

### ProtocolLib Version

5.1.0-SNAPSHOT-661

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
Strange.
This will be checked as soon as possible. Thanks for the patience.

**Comment by LoneDev6** [comment]
Will be fixed, thanks!
Note: in the next update if you scroll your items during a recording they won't replace your equipment. The equipment will remain the same set in the spawn event of the NPC. Do not specify any equipment if you want items to be replaced by the selected ones during scrolling.
