### ISSUE TITLE
The config file generated by the plugin and also within the Jar is inavlid

### ISSUE THREAD

**Issue by ofunny** [PluginBugs/Issues-CinematicStudio#55]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

ofunny

### What happened?

The config file that will be created by the plugin and also the default config within the jar file is invalid, it just has +/- 1KB and contains either binary or another unreadable format. Can not be opened via regular text/code editor.

### Steps to reproduce the issue

1. Remove CinematiStudio and it's folder from your test server.
2. Install it from scratch
3. Try to open the fresh generated config file

### Server version

Paper version git-Paper-196 (MC: 1.20.1)

### CinematicsStudio Version

CinematicStudio version 1.4.4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-668

### LoneLibs Version

LoneLibs version 1.0.26

### FULL server log

On request, contains nothing special.

### CinematicsStudio config.yml

```shell
Not readable
```

**Comment by LoneDev6** [comment]
The config file is just a placeholder, there is no setting for this plugin for now
