### ISSUE TITLE
Potential IO issues

### ISSUE THREAD

**Issue by GsTio86** [PluginBugs/Issues-CinematicStudio#58]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

galen86

### What happened?

First I am developing a player data synchronization addon (HuskSync API) for this plugin
Since the plugin operates player data through asyn scheduling, husksync also
Therefore, when I implement them, I may conflict with the original files or even destroy them.

The main reason is that it performs IO operations on the same file instead of a single key

### Steps to reproduce the issue

N/A

### Server version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/74390539/f2e074c6-930a-4dc7-80a8-d4ac994f580f)

### CinematicsStudio Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/74390539/ad3f38d1-4ccb-4f61-b172-8e9935e90783)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/74390539/465fd6b3-7b83-4847-be1c-517813dbd209)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CinematicsStudio/assets/74390539/49c1daf9-a574-408b-b63e-3e1604390baf)

**Comment by LoneDev6** [comment]
Can you make an example about which CinematicStudio files are causing this issue?

**Comment by GsTio86** [comment]
> Can you make an example about which CinematicStudio files are causing this issue?

The main reason is that CinematicStudio re-calls player_data multiple times asynchronously, and my HuskSyncAddon is also implemented through asynchronous processing.
If you write and read the file at the same time, it is very likely that the data will be out of sync.

**Comment by LoneDev6** [comment]
What do you mean by "player_data"? The CinematicStudio files or Minecraft player data in world folder?

**Comment by GsTio86** [comment]
> CinematicStudio files

CinematicStudio files
