### ISSUE TITLE
Add custom model data items to NPC equipment.

### ISSUE THREAD

**Issue by WasaTG** [PluginBugs/Issues-CinematicStudio#70]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

elcory

### Describe the solution you'd like

Add custom model data items to NPC equipment. To be able to equip the NPC with the armor, masks and weapons created with ItemsAdder

### Is your feature request related to a problem?

https://github.com/PluginBugs/Issues-CinematicStudio/assets/91429437/2d8f4acc-815a-4372-89c7-ea8b71ea2a3f

When I want to add items created in ItemsAdder to the NPC's equipment, the textures it shows are the default ones.

### Describe alternatives you've considered

Add custom model data items to NPC equipment. To be able to equip the NPC with the armor, masks and weapons created with ItemsAdder

**Comment by LoneDev6** [comment]
v2 will support direct NBT settings so you can put any item you want:
```json
  "equipment": {
    "HEAD": "{Count:1b,id:\"minecraft:netherite_helmet\",tag:{Damage:27}}",
    "CHEST": "{Count:1b,id:\"minecraft:elytra\",tag:{Damage:0}}",
    "HAND": "{Count:1b,id:\"minecraft:diamond_sword\",tag:{Damage:0}}"
  },
```
