### ISSUE TITLE
Optifine incompat - Player appearing when moving cam foward

### ISSUE THREAD

**Issue by Sty13** [PluginBugs/Issues-CinematicStudio#74]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

sty13

### What happened?

The player with pumpkin on their head appears on front of the cinematic camera (Only when using the smooth movement type)

https://youtu.be/ec1YwyTlGLI

### Steps to reproduce the issue

1. Create a purpur 1.20.2 server
2. Join the server with optifine 1.20.2
3. Create a cinematic with smooth cameras

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-1814 (MC: 1.19.2)
* You are running the latest version

### CinematicsStudio Version

CinematicStudio version 1.4.6
[02:26:31 INFO]: Cutscene Tool to create advanced cutscenes
[02:26:31 INFO]: Authors: LoneDev and CraterHater

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679
[02:26:55 INFO]: Provides read/write access to the Minecraft protocol.
[02:26:55 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.45
[02:27:14 INFO]: Collection of libs used by my plugins
[02:27:14 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CinematicStudio/files/14320901/latest.log)

### CinematicsStudio config.yml

```shell
can't open (Idk why) but it's the one that is generated with the plugin
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/ec1YwyTlGLI

**Comment by LoneDev6** [comment]
I will install optifine and test, anyway no one is using optifine anymore because it's flawed and doesn't boost performance.
Everyone is using modpacks to achieve optimized Minecraft gameplay.
Example: https://www.curseforge.com/minecraft/modpacks/fabulously-optimized
