### ISSUE TITLE
[SUGGESTION] Rotations

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-CinematicStudio#75]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

asleepp

### Describe the solution you'd like

I think it'd be a great idea to implement rotations, as that'd allow for a lot more "cinematic" approaches. Example: Replay mod allows this. For how the player would set the rotation, is another thing. I don't know how you would do that.

### Is your feature request related to a problem?

Nope.

### Describe alternatives you've considered

There is none.

**Comment by LoneDev6** [comment]
Can you share a video or a web page explaining what you'd expect?
Or try to explain it with some drawing.

Thanks!

**Comment by Asleeepp** [comment]
> Can you share a video or a web page explaining what you'd expect? Or try to explain it with some drawing.

In Replay mod you can do this easily, now I know you can't really do it like replay mod in vanilla minecraft, but i think optionally setting a rotation degree with a command or something along those lines would be really cool

https://github.com/PluginBugs/Issues-CinematicStudio/assets/119438940/a01bf01b-0dc7-4858-a942-84ae7046fee0

**Comment by Asleeepp** [comment]
> Basically what you are requesting is rotation on the X axis, correct?
> 
> Because this is not possible in any way in Minecraft due to how the engine works.
> 
> There is no packet to send _roll_ (x axis) rotation.
> 

oh, thats a shame.
