### ISSUE TITLE
Please add this plugin on PolyMart

### ISSUE THREAD

**Issue by witcharon** [PluginBugs/Issues-CinematicStudio#77]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, I cannot purchase the add-on through Spigot because PayPal is not used in my country. I would like to buy it if you introduce payment support with PolyMart and Stripe.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

I would like to buy it if you introduce payment support with PolyMart and Stripe.

**Comment by LoneDev6** [comment]
Might be added in the future when v2 will be released, thanks
