### ISSUE TITLE
Newest LoneLibs support

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-CinematicStudio#92]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

PSYCHEER

### What happened?

[latest.log](https://github.com/user-attachments/files/15889903/latest.log)

### Steps to reproduce the issue

update into newest lonelibs
check the log

### Server version

![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/42911029/d5fcd6e1-ef94-437c-baaa-010c0653a052)

### CinematicsStudio Version

![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/42911029/9ae8f146-a9ca-4b20-bf8a-e5ce8fae244d)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/42911029/c779fc6a-5e95-48f5-9895-4ede9b5f9fb1)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/42911029/a64b669e-b2cf-4501-be98-dcbb4fa3fa79)

### FULL server log

You have it over there

### CinematicsStudio config.yml

```shell
messages:
  settings:
    lang: en
    extract_default_language_files: true
  debug:
    enabled: false
cinematics:
  graphics:
    pumpkin:
      custom_model_data: 3000001
      display_name: ''
    wandering_trader_egg:
      custom_model_data: 3000001
      display_name: ''
gui:
  use_resourcepack: true
```

**Comment by Andre601** [comment]
Use a paste site next time, because nobody likes downloading log files: https://mclo.gs/epCeAdO

**Comment by Andre601** [comment]
Also, your main issue is here, which has nothing hinting at LoneLibs being the issue, but rather just trying to use CS on an unsupported server version: https://mclo.gs/epCeAdO#L256

**Comment by PSYCHEER** [comment]
Tested on clean test server as well, after that, I was waiting for CosmeticsCore so I can update from LoneLibs 46 to 54 and this issue is caused by newest LoneLibs

**Comment by PSYCHEER** [comment]
> Use a paste site next time, because nobody likes downloading log files: https://mclo.gs/epCeAdO

And sorry about that, I didn't realized GitHub does give it as file download instead of showing it😄

**Comment by intersecato** [comment]
> Also, your main issue is here, which has nothing hinting at LoneLibs being the issue, but rather just trying to use CS on an unsupported server version: https://mclo.gs/epCeAdO#L256

bro we are running 1.20.4 how it could be unsupported if it is written in supported versions
