### ISSUE TITLE
1.21 support 

### ISSUE THREAD

**Issue by Logan8642** [PluginBugs/Issues-CinematicStudio#95]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add 1.21 support Please.

### Is your feature request related to a problem?

Please add 1.21 support so updated servers can use this amazing plugin.

### Describe alternatives you've considered

not relevant

**Comment by TheMrLhuixx** [comment]
+1

**Comment by 44wrw44** [comment]
+1
